all: SORT

SORT: merge_sort.c mergeinsert_sort.c bubble_sort.c comb_sort.c insertion_sort.c selection_sort.c shell_sort.c
	gcc merge_sort.c -o merge_sort
	gcc mergeinsert_sort.c -o mergeinsert_sort
	gcc bubble_sort.c -o bubble_sort
	gcc comb_sort.c -o comb_sort
	gcc insertion_sort.c -o insertion_sort
	gcc selection_sort.c -o selection_sort
	gcc shell_sort.c -o shell_sort
